version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: iamafateson2
      MYSQL_DATABASE: xblog
      MYSQL_USER: zyf
      MYSQL_PASSWORD: iamafateson2

  php:
    depends_on:
      - mysql
    image: tommylau/php:7.1
    volumes:
      - $PWD:/var/www
    restart: always

  nginx:
    depends_on:
      - php
    image: nginx:1.12-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD:/var/www
      - $PWD/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  data: